# Generated by Django 4.0.10 on 2026-09-08 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
