# Generated by Django 4.0.10 on 2026-09-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='make_public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
